"""Stage-level character timeline: one JSON for each character, storing incremental delta by (chapter, stage).

The timeline is an intermediate product generated by LLM, the only true value, and can be modified manually. Each snapshot only stores this stage
Changing fields (delta). The fold (initial + accumulation) is taken care of by character_resolver.
Persisted in chronos.sqlite3 timeline_snapshots table. Coordinates internally by character_id
(FK into lore_characters) -- every function here keeps its public name-based signature, name/id
resolution is entirely internal (_char_id)."""
from __future__ import annotations

from typing import Any, cast

from repositories.engine import session_for
from repositories.models import LoreCharacter, TimelineSnapshot
from sqlalchemy import delete, func
from sqlmodel import Session, col, select


def _char_id(session: Session, name: str) -> int | None:
    return session.exec(
        select(LoreCharacter.id).where(col(LoreCharacter.name) == name)
    ).one_or_none()


def _coord(s: dict) -> tuple[int, int]:
    return (int(s.get("chapter", 0)), int(s.get("stage", 0)))


def load_timeline(name: str) -> dict[str, Any]:
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            return {"name": name, "snapshots": []}
        rows = s.exec(
            select(
                TimelineSnapshot.chapter, TimelineSnapshot.stage, TimelineSnapshot.delta_json
            )
            .where(col(TimelineSnapshot.character_id) == cid)
            .order_by(col(TimelineSnapshot.chapter), col(TimelineSnapshot.stage))
        ).all()
    return {
        "name": name,
        "snapshots": [{"chapter": c, "stage": st, "delta": dict(d)} for c, st, d in rows],
    }


def append_stage(name: str, chapter: int, stage: int, delta: dict) -> None:
    """Write/overwrite the delta of a (chapter,stage). If the same coordinate already exists, replace it."""
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            raise ValueError(f"角色「{name}」不在花名册中，无法写入 timeline。")
        row = s.get(TimelineSnapshot, (cid, chapter, stage))
        if row is None:
            s.add(TimelineSnapshot(character_id=cid, chapter=chapter, stage=stage, delta_json=delta))
        else:
            row.delta_json = delta
        s.commit()


def _save(tl: dict[str, Any]) -> None:
    """Replace all snapshots for this character (bulk rewrite after one-off migration scripts)."""
    name = str(tl["name"])
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            raise ValueError(f"角色「{name}」不在花名册中，无法写入 timeline。")
        s.exec(delete(TimelineSnapshot).where(col(TimelineSnapshot.character_id) == cid))
        for snap in tl.get("snapshots") or []:
            s.add(TimelineSnapshot(
                character_id=cid,
                chapter=int(snap.get("chapter", 0)),
                stage=int(snap.get("stage", 0)),
                delta_json=snap.get("delta") or {},
            ))
        s.commit()


def get_stage(name: str, chapter: int, stage: int) -> dict | None:
    """The snapshot at this exact (chapter,stage) coordinate, or None if absent -- used to
    capture a rollback point before a speculative append_stage (see remove_stage)."""
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            return None
        row = s.get(TimelineSnapshot, (cid, chapter, stage))
        if row is None:
            return None
        return {"chapter": chapter, "stage": stage, "delta": dict(row.delta_json)}


def remove_stage(name: str, chapter: int, stage: int) -> None:
    """Drop the snapshot at this exact (chapter,stage) coordinate, if present. No-op if absent
    (including when the character itself is unknown)."""
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            return
        row = s.get(TimelineSnapshot, (cid, chapter, stage))
        if row is not None:
            s.delete(row)
            s.commit()


def deltas_upto(name: str, chapter: int, stage: int) -> list[dict]:
    """All snapshots (inclusive) with (c,s) <= (chapter,stage), in ascending order of coordinates."""
    return [s for s in load_timeline(name)["snapshots"] if _coord(s) <= (chapter, stage)]


def deltas_before(name: str, chapter: int, stage: int) -> list[dict]:
    """All snapshots (exclusive) (c,s) < (chapter,stage), in ascending order of coordinates."""
    return [s for s in load_timeline(name)["snapshots"] if _coord(s) < (chapter, stage)]


def get_current(name: str) -> dict | None:
    snaps = load_timeline(name)["snapshots"]
    return cast(dict | None, snaps[-1] if snaps else None)


def latest_chapter(name: str) -> int:
    """The maximum chapter number that this character's timeline has been built to; returns 0
    if it has never been built (including when the character itself is unknown)."""
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            return 0
        val = s.exec(
            select(func.max(col(TimelineSnapshot.chapter)))
            .where(col(TimelineSnapshot.character_id) == cid)
        ).one()
    return int(val) if val is not None else 0


def truncate_from(name: str, from_chapter: int) -> int:
    """Delete the snapshots of chapter >= from_chapter in the character's timeline and return
    the number of deleted items. 0 (not an error) if the character is unknown -- this is the
    normal shape when called after the character's lore_characters row was already removed
    (see tools.py's delete_character flow, which deletes the roster row before cleaning up
    archives/timeline)."""
    with session_for() as s:
        cid = _char_id(s, name)
        if cid is None:
            return 0
        removed = s.exec(
            select(func.count()).select_from(TimelineSnapshot).where(
                col(TimelineSnapshot.character_id) == cid,
                col(TimelineSnapshot.chapter) >= from_chapter,
            )
        ).one()
        if removed:
            s.exec(
                delete(TimelineSnapshot).where(
                    col(TimelineSnapshot.character_id) == cid,
                    col(TimelineSnapshot.chapter) >= from_chapter,
                )
            )
            s.commit()
    return int(removed)


def list_timeline_names() -> list[str]:
    """All character names that have rows in timeline_snapshots (empty if none)."""
    with session_for() as s:
        rows = s.exec(
            select(LoreCharacter.name)
            .join(TimelineSnapshot, col(LoreCharacter.id) == col(TimelineSnapshot.character_id))
            .distinct()
        ).all()
    return list(rows)
