"""Stage-level character timeline: one JSON for each character, storing incremental delta by (chapter, stage).

The timeline is an intermediate product generated by LLM, the only true value, and can be modified manually. Each snapshot only stores this stage
Changing fields (delta). The fold (initial + accumulation) is taken care of by character_resolver.
Persisted in chronos.sqlite3 timeline_snapshots table."""
from __future__ import annotations

import json
import os
import sqlite3
from typing import Any, cast

from repositories.sqlite_store import get_connection
from utils.paths import active_novel_id, novel_dir


def _conn() -> sqlite3.Connection:
    path = os.path.join(novel_dir(active_novel_id()), "chronos.sqlite3")
    return get_connection(path)


def _coord(s: dict) -> tuple[int, int]:
    return (int(s.get("chapter", 0)), int(s.get("stage", 0)))


def load_timeline(name: str) -> dict[str, Any]:
    rows = _conn().execute(
        "SELECT chapter, stage, delta_json FROM timeline_snapshots"
        " WHERE name = ? ORDER BY chapter, stage",
        (name,),
    ).fetchall()
    snapshots = [
        {"chapter": c, "stage": s, "delta": json.loads(d)}
        for c, s, d in rows
    ]
    return {"name": name, "snapshots": snapshots}


def append_stage(name: str, chapter: int, stage: int, delta: dict) -> None:
    """Write/overwrite the delta of a (chapter,stage). If the same coordinate already exists, replace it."""
    conn = _conn()
    conn.execute(
        "INSERT OR REPLACE INTO timeline_snapshots (name, chapter, stage, delta_json)"
        " VALUES (?, ?, ?, ?)",
        (name, chapter, stage, json.dumps(delta, ensure_ascii=False)),
    )
    conn.commit()


def _save(tl: dict[str, Any]) -> None:
    """Replace all snapshots for this character (bulk rewrite after one-off migration scripts)."""
    name = str(tl["name"])
    conn = _conn()
    conn.execute("DELETE FROM timeline_snapshots WHERE name = ?", (name,))
    for snap in tl.get("snapshots") or []:
        conn.execute(
            "INSERT INTO timeline_snapshots (name, chapter, stage, delta_json)"
            " VALUES (?, ?, ?, ?)",
            (
                name,
                int(snap.get("chapter", 0)),
                int(snap.get("stage", 0)),
                json.dumps(snap.get("delta") or {}, ensure_ascii=False),
            ),
        )
    conn.commit()


def get_stage(name: str, chapter: int, stage: int) -> dict | None:
    """The snapshot at this exact (chapter,stage) coordinate, or None if absent -- used to
    capture a rollback point before a speculative append_stage (see remove_stage)."""
    row = _conn().execute(
        "SELECT delta_json FROM timeline_snapshots WHERE name = ? AND chapter = ? AND stage = ?",
        (name, chapter, stage),
    ).fetchone()
    if row is None:
        return None
    return {"chapter": chapter, "stage": stage, "delta": json.loads(row[0])}


def remove_stage(name: str, chapter: int, stage: int) -> None:
    """Drop the snapshot at this exact (chapter,stage) coordinate, if present. No-op if absent.
    Counterpart to append_stage -- used to roll back a speculative write (e.g. _write_timeline_
    delta appends the new delta before validating the resolved archive; if validation then
    rejects it, the timeline must not be left holding a delta whose archive was never persisted,
    or missing_timeline_targets will permanently consider that chapter already built and never
    offer to rebuild it)."""
    conn = _conn()
    conn.execute(
        "DELETE FROM timeline_snapshots WHERE name = ? AND chapter = ? AND stage = ?",
        (name, chapter, stage),
    )
    conn.commit()


def deltas_upto(name: str, chapter: int, stage: int) -> list[dict]:
    """
All snapshots (inclusive) with (c,s) ≤ (chapter,stage), in ascending order of coordinates."""
    return [s for s in load_timeline(name)["snapshots"] if _coord(s) <= (chapter, stage)]


def deltas_before(name: str, chapter: int, stage: int) -> list[dict]:
    """All snapshots (exclusive) (c,s) < (chapter,stage), in ascending order of coordinates."""
    return [s for s in load_timeline(name)["snapshots"] if _coord(s) < (chapter, stage)]


def get_current(name: str) -> dict | None:
    snaps = load_timeline(name)["snapshots"]
    return cast(dict | None, snaps[-1] if snaps else None)


def latest_chapter(name: str) -> int:
    """
The maximum chapter number that this character's timeline has been built to; returns 0 if it has never been built."""
    row = _conn().execute(
        "SELECT MAX(chapter) FROM timeline_snapshots WHERE name = ?",
        (name,),
    ).fetchone()
    if row is None or row[0] is None:
        return 0
    return int(row[0])


def truncate_from(name: str, from_chapter: int) -> int:
    """Delete the snapshots of chapter >= from_chapter in the character's timeline and return the number of deleted items.

    To delete chapter N and thereafter, use: scroll under fold, leaving the old high chapter delta will contaminate the reconstruction, so it is cleared jointly and severally."""
    conn = _conn()
    row = conn.execute(
        "SELECT COUNT(*) FROM timeline_snapshots WHERE name = ? AND chapter >= ?",
        (name, from_chapter),
    ).fetchone()
    removed = int(row[0]) if row else 0
    if removed:
        conn.execute(
            "DELETE FROM timeline_snapshots WHERE name = ? AND chapter >= ?",
            (name, from_chapter),
        )
        conn.commit()
    return removed


def list_timeline_names() -> list[str]:
    """
active is the character name of the timeline that has rows in timeline_snapshots (empty if none)."""
    rows = _conn().execute(
        "SELECT DISTINCT name FROM timeline_snapshots",
    ).fetchall()
    return [r[0] for r in rows]
