"""Repository access layer interface. Consumers rely on these protocols and do not rely on specific implementations (tests can inject fake implementations)."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from repositories.entities import (
    ChapterOutline,
    Character,
    CharacterArchive,
    ResearchChunk,
)


@runtime_checkable
class LoreRepository(Protocol):
    def get_character(self, name: str) -> Character | None: ...
    def list_characters(self) -> list[Character]: ...


@runtime_checkable
class PlotRepository(Protocol):
    def get_outline(self, chapter: int) -> ChapterOutline | None: ...
    def chapter_segments(self, chapter: int) -> tuple[str | None, list[dict]]: ...
    def chapter_core_xp(self, chapter: int) -> list[str]: ...


@runtime_checkable
class ArchiveRepository(Protocol):
    def get(self, name: str, chapter: int) -> CharacterArchive | None: ...
    def put(self, name: str, chapter: int, archive: dict) -> None: ...
    def preload(self, chapter: int) -> dict[str, dict]: ...
    def evict_from(self, chapter: int) -> int: ...


@runtime_checkable
class ResearchRepository(Protocol):
    def query(self, topic: str, top_k: int) -> list[ResearchChunk]: ...
    def upsert(self, chunks: list[ResearchChunk]) -> int: ...
    def replace_for_source(self, source: str, chunks: list[ResearchChunk]) -> int: ...
    def get_chunks(self, category: str, topic: str | None = None) -> list[ResearchChunk]: ...
    def list_topics(self, category: str) -> list[str]: ...
