
export interface WorldBuildState {
  status: 'idle' | 'building' | 'done' | 'error'
  sections: string[]
  errors: string[]
  path?: string
  error?: string
  schema?: {
    status: 'building' | 'done' | 'error'
    roles?: string[]
    errors?: string[]
  }
}

export interface PlotBuildState {
  status: 'idle' | 'building' | 'done' | 'error'
  chapterCount: number
  errors: string[]
  path?: string
  error?: string
}

/** Main writing output: one beat (single section is cut into multiple beats, written beat by beat). draft=A draft that is still under "Satisfaction/Rewrite" consultation.*/
export interface AuthorSegment {
  index: number      //The segment number to which it belongs
  beat?: number      //beat sequence number (within segment, base 0); default = single beat in the entire segment
  beats?: number     //The total number of beats in this segment
  intent: string
  skill: string | null
  text: string
  draft?: boolean
  agent?: string   //dialogue mode output party (director/character/synthesis)
  role?: string    //The character name when agent=character
  psychology?: string  //Psychological activities when agent=character
}

/** A message in the conversation timeline (chat record: left = agent, right = user, saved in order of arrival).*/
/** Deduce the current runtime state (psychological/postural/attire/action/demeanor) of a
 * character produced by the agent. */
export type ScoredDescValue = { score: number; desc: string }

export interface StateDeriveFieldSpec {
  key: string
  label: string
  kind: 'text' | 'scored_desc'
}

export interface CharacterState {
  name: string
  psychology?: string
  posture?: string
  clothing?: string
  action?: string
  demeanor?: string
  [field: string]: string | ScoredDescValue | undefined
}

export type EventLogEntry = {
  id?: string
  summary: string
  time: string
  location?: string
  characters?: string[]
}

export type AuthorMessage =
  | { id: string; role: 'agent'; type: 'segment'; segment: AuthorSegment }
  | { id: string; role: 'agent'; type: 'state'; characters: CharacterState[]; entry?: boolean }  //Deduction: character state (entry = entry state before running)
  | { id: string; role: 'agent'; type: 'summary'; text: string }                //Summary: Summary of this beat
  | { id: string; role: 'agent'; type: 'event_log'; events: EventLogEntry[] }   //Archived memory-recall events for this stage
  | { id: string; role: 'agent'; type: 'recall'; recallContext: string }        //Pre-generation memory recall result for this stage

export interface AuthorLoopState {
  status: 'idle' | 'running' | 'done' | 'error'
  chapter: number
  total: number
  messages: AuthorMessage[]      //Dialogue timeline (segment/state/summary, retained throughout)
  progress?: { agent: string; attempt: number; attempts: number } | null  //Current LLM call heartbeat (agent label + number of attempts)
  chapterProgress?: { done: number; total: number } | null  //The total beat-level progress of the entire chapter (completed/total number of beats), driving the progress bar
  live?: { agent: string; text: string; role?: string }[] | null  //Main flow: the visible content (narration/lines/synthesis) being generated by each agent of this beat, one for each agent coexists, and will be cleared after finalization; role=line agent role name (live bubble label name)
  styleRewriting?: { agent: string; role?: string } | null  //Style-guard rewrite in progress for one agent bubble
  stalled?: boolean              //watchdog: running exceeds the threshold without any events → soft alarm "suspected to be stuck"
  error?: string
}

export interface ArchiveOverview {
  built: { chapter: number; characters: string[] }[]
  plot_chapters: { chapter: number; roster: string[]; built: string[] }[]
}
export interface SliderLevelText {
  level: number
  text: string
}
export interface RenderedSlider {
  value: number | string | SliderLevelText
  label: string
}
export interface ArchiveStage {
  location?: string
  gender?: string
  sliders: Record<string, RenderedSlider>
  physique?: Record<string, string>
  personality?: string
  // Ref-pool fields: newer data is bucketed by target/context as { bucket: [terms...] }
  // (self_ref uses bucket "_default" for general context). Legacy data can be a flat
  // `string` (and `self_ref` was also seen as a bare `string[]`). All shapes coexist
  // in historical archives, so the rendering layer must handle every variant.
  address_ref?: string | Record<string, string[]>
  self_ref?: string | string[] | Record<string, string[]>
  thought_process?: { delta?: string; escalation?: string }
  hobbies?: string[]
  verbal_tic?: string
  identity_background?: string
}
// Flat: one profile per chapter (no per-stage nesting) -- base identity fields plus every
// ArchiveStage field sit side by side at the top level.
export interface CharacterArchive extends ArchiveStage {
  name: string
  role: string
  causal_anchors: Record<string, unknown>
}
export interface ChapterArchives { chapter: number; characters: CharacterArchive[] }

export type SandboxMemoryEntry = {
  id: string
  chapter: number
  turnIndex: number
  time: string
  location: string
  characters: string[]
  summary: string
  entities: string[]
  branchId: string | null
}

// Relationship-graph edge: from/to are given_name strings. Direction only marks which side
// recorded the relationship first -- it does not imply dominance. ref_terms are third-person
// relational terms (e.g. "师傅"/"妹妹") distinct from the given_name, see
// docs/superpowers/specs/2026-07-20-sandbox-relation-term-entity-alias-design.md.
export interface RelationshipEdge {
  from: string
  to: string
  nature: string
  relationship_anchor?: string
  from_ref_terms?: string[]
  to_ref_terms?: string[]
}
export interface RelationshipGraph {
  groups: Record<string, unknown>
  edges: Record<string, RelationshipEdge>
}

export interface WorldNamedItem {
  name: string
  desc: string
  // Trigger keywords for recall (see engine/memory_recall/recall.py) -- only power_system/
  // core_themes entries are actually consumed by the recall gate, but the field lives on the
  // shared shape since that's how the backend schema (WorldNamedItemArgs) declares it too.
  keywords?: string[]
}
export interface WorldBible {
  tone?: string
  background?: string
  factions?: WorldNamedItem[]
  geography?: WorldNamedItem[]
  races?: WorldNamedItem[]
  power_system?: WorldNamedItem[]
  core_themes?: WorldNamedItem[]
}
export interface SetupWorld {
  world_bible: WorldBible | null
}
export interface CustomFieldSpec {
  name: string
  required: boolean
  timeline_delta: boolean
}
export interface CastCharacter {
  name: string
  given_name?: string
  role?: string
  identity?: string
  gender?: string
  causal_anchors?: Record<string, string>
  sliders?: Record<string, string | { level: number; text: string; levels?: Record<string, string> }>
  physique?: Record<string, string>
  clothing_dna?: {
    color_palette?: string[]
    materials_preference?: string[]
    signature_outfit?: string
    accessories?: string[]
  }
  race?: string
  identity_background?: string
  hobbies?: string[]
  verbal_tic?: string
  personality?: string
  portrait_path?: string
  portrait_visual_tags?: string
  portrait_identity_tags?: string
}
export type CastCharacterInput = Pick<
  CastCharacter,
  'given_name' | 'role' | 'gender' | 'causal_anchors' | 'physique' | 'personality' | 'sliders'
> & {
  clothing_color_palette: string[]
  clothing_materials: string[]
  clothing_signature_outfit: string
  clothing_accessories: string[]
  race?: string
  identity_background?: string
  hobbies?: string[]
  verbal_tic?: string
  portrait_visual_tags?: string
  portrait_identity_tags?: string
} & Record<string, string | string[] | Record<string, string> | Record<string, string | { level: number; text: string; levels?: Record<string, string> }> | undefined>
export interface PlotStage {
  stage_num: number
  title?: string
  location?: string
  description?: string
  characters?: Record<string, Record<string, never>>
}
export interface PlotChapter {
  chapter: number
  title?: string
  core_xp?: string[]
  stages?: PlotStage[]
}
