"""Cast product placement: write character_lore_library.json for overall coverage, and write through LoreRepository.

per-story creates the entire class at once, non-incrementally; JsonStore._atomic_write_json ensures atomicity (write the temporary file first and then os.replace).
Theme-specific body alienation (story_character_config.json) is not generated by the engine and is left to the user/external agent for personalization."""
from __future__ import annotations

from typing import Any


def write_cast(
    roster: list[dict[str, Any]],
    *,
    library_path: str | None = None,
) -> str:
    """
Download all class character files and return library_path."""
    from repositories import get_lore_repo
    from utils.paths import lore_library_path

    get_lore_repo().save_all(roster, path=library_path)

    from engine.memory_recall.entity_index import invalidate_entity_vocab_cache

    invalidate_entity_vocab_cache()
    return library_path or lore_library_path()
