"""cast parsing of two rounds of LLM output + skeleton ↔ deep merge (driver I/O contract, pure function).

Both rounds agree to output an array of JSON objects (parse_embed_json is reused for fault-tolerant parsing):
- Round0 skeleton: each element contains given_name/role/gender/relationship_to_lead/causal_anchors
- Round1 deep file: each element contains given_name(+) physique/clothing_dna/sliders

merge_cast matches the given_name to form the complete character file (character_lore_library) of the downstream lore.
Theme-specific body alienation (story_character_config) is not generated by the engine and is left to the user/external agent for personalization.
relationship_to_lead is only for generating assistance (feeding the next round) and does not enter the final lore."""
from __future__ import annotations

from typing import Any

from engine.execution.embed_json import parse_embed_json

#Enter the skeleton field of the final lore (relationship_to_lead is a generation auxiliary, not included)
_SKELETON_FIELDS = ("role", "gender", "causal_anchors", "race")
_DEEPDIVE_FIELDS = ("physique", "clothing_dna", "sliders")


def parse_round(raw: str) -> list[dict]:
    """
The output of one round of fault-tolerant parsing is an object array (reusing the weak model fault-tolerant parsing of embed_splice)."""
    return parse_embed_json(raw)


def _name_of(obj: dict) -> str:
    return str(obj.get("given_name") or obj.get("name") or "").strip()


def merge_cast(skeleton: list[dict], deepdive: list[dict]) -> list[dict]:
    """Match the skeleton and profile according to the given_name to complete the character profile list.

    When a role is missing in the deep file, the role only has skeleton fields (the verification phase will determine that the schema is incomplete and trigger redo)."""

    dd_by_name = {_name_of(d): d for d in deepdive if _name_of(d)}
    roster: list[dict] = []
    for sk in skeleton:
        name = _name_of(sk)
        if not name:
            continue
        dd = dd_by_name.get(name, {})
        char: dict[str, Any] = {"name": name, "given_name": name}
        for k in _SKELETON_FIELDS:
            if k in sk:
                char[k] = sk[k]
        for k in _DEEPDIVE_FIELDS:
            if k in dd:
                char[k] = dd[k]
        roster.append(char)
    return roster
