"""Grounding generated by plot: cast list + causal + world_bible summary.

The stage character name can only take the cast list (hard requirement of validate_plot), so the list must be fed into the prompt.
Personality is derived from timeline and plot no longer declares it. world_bible is optional (fits the world), if missing, it will be downgraded."""
from __future__ import annotations

import json
from typing import Any


def load_plot_grounding() -> dict[str, Any]:
    """
Return {character_names, cast_text, world_text}. If the cast list is empty, an error will be reported, and it will be accelerated by Lore/World Repositories caching."""
    from repositories import get_lore_repo, get_world_repo

    from engine.setup.world.summary import render_world_summary

    chars = [c.model_dump() for c in get_lore_repo().list_characters()]
    names = [c["name"] for c in chars if c.get("name")]
    if not names:
        raise ValueError("当前小说没有角色（character_lore_library 为空），请先「构建人物设定」")

    cast_lines = []
    for c in chars:
        if not c.get("name"):
            continue
        ca = c.get("causal_anchors") or {}
        role = c.get("role", "")
        cast_lines.append(f"- {c['name']}（{role}）：{json.dumps(ca, ensure_ascii=False)}")
    cast_text = "\n".join(cast_lines)

    bible = get_world_repo().get()
    world_text = render_world_summary(bible or {})

    return {
        "character_names": names,
        "cast_text": cast_text,
        "world_text": world_text,
    }
